-- CREATE DATABASE PERSONAS 
USE PERSONAS;
-- CREATE TABLE PERSONA(ID_PERSONA INT PRIMARY KEY, NOMBRE VARCHAR(20), APELLIDO VARCHAR(20));
-- INSERT INTO PERSONA(ID_PERSONA, NOMBRE, APELLIDO) VALUES(1,"JUAN","PEREZ");
-- SELECT * FROM PERSONA
-- SELECT NOMBRE FROM PERSONA
-- INSERT INTO PERSONA(ID_PERSONA, NOMBRE, APELLIDO) VALUES(2,"MARÍA","GOMEZ");
-- INSERT INTO PERSONA(ID_PERSONA, NOMBRE, APELLIDO) VALUES(3,"MARCOS","RODRIGUEZ");
-- SELECT * FROM PERSONA WHERE ID_PERSONA = 2